name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - run: sudo apt update && sudo apt install -y libpam0g-dev

    - name: Build binary
      run: go build -o chpass-web

    - name: Run unit tests
      run: go test -count=1 ./...
